# self-supervised motion labels
visualize: False
sequences: [1]
# path to dataset
path_dataset: /disk/vanishing_data/ju878/dataset/sequences
# path to inference folder
path_inference: /disk/vanishing_data/ju878/test_odometry


