path_dataset: /disk/vanishing_data/ju878/CODA_for_detection_method/sequences
path_inference: /disk/vanishing_data/ju878/inference
sequences:
- 1
- 2
- 3
- 4
- 5
- 1058
- 1059
- 1060
- 1061
- 1062
- 1366
- 1367
- 1371
- 1372
- 1373
visualize: false
