# self-supervised motion labels
visualize: False
sequences: [11,12,13,14,15,16,17,18,19,20,21]
# path to dataset
path_dataset: /data/dataset/sequences
# path to inference folder
path_inference: /data/inference


